[package]
name = "rust-ai-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
throw = "0.1.7"
sdl2 = "0.35.2"
rstar = "0.11.0"
